app:
  name: "web_app"
  mode: "dev"
  host: "127.0.0.1"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "192.168.222.131"
  port: 3306
  user: "root"
  password: "123456"
  db_name: "test"
  max_open_conns: 200
  max_idle_conns: 10

redis:
  host: "192.168.222.131"
  port: 6379
  db: 0
  password: "123456"
  pool_size: 100