# yaml 配置
version: "3.7"
services:
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /models/create_table.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root123456"
      MYSQL_DATABASE: "bubble"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./init.sql:/models/create_table.sql
  redis507:
    image: "redis:5.0.7"
    ports:
      - "6379:6379"
  bluebell:
    build: .
    command: sh -c "./wait-for.sh mysql8019:3306 redis507:6379 -- ./bluebell ./conf/config.yaml"
    depends_on:
      - mysql8019
      - redis507
    ports:
      - "8888:8082"